### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock' 

### ISSUE THREAD

**Issue by juhele** [OpenGeoLabs/qgis-safecast-plugin#5]
After upgrade to Kubuntu 20.04 LTS the development version of Safecast plugin for QGIS3 stopped working:

```
An error has occurred while executing Python code: 

AttributeError: module 'time' has no attribute 'clock' 
Traceback (most recent call last):
  File "/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/radiation_toolbox_dockwidget.py", line 404, in onLoad
    layer.load(reader)
  File "/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/layer/safecast.py", line 96, in load
    super(SafecastLayer, self).load(reader)
  File "/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/layer/__init__.py", line 80, in load
    start = time.clock()
AttributeError: module 'time' has no attribute 'clock'


Python version: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0] 
QGIS version: 3.12.3-București București, 8234261527 

Python Path:
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/layer/..
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-radiation-toolbox-plugin-master/layer/..
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-safecast-plugin-master/layer/..
/usr/share/qgis/python
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python
/home/juhele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs
```
Googled a little bit and it seems to be caused by the fact that time.clock() was removed from new Python version:

https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8

**Comment by juhele** [comment]
Solution suggested by one of our users and based on:
https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8
involves replecing "time.clock()" with "time.perf_counter()" in two files:

/layer/__init__.py
/layer/safecast.py

Loading LOG files works after this fix and  calculated local time column seems to be correct too.
Will do more testing.

**Comment by landam** [comment]
This repository contains QGIS2 safecast plugin. It's not relevant for current version.

**Comment by landam** [comment]
@juhele Fixed in development repository.
